name: build libMacportsLegacySystem.B.dylib on macOS ARM runner

on:
  workflow_dispatch: 

jobs:
  build:
    name: build
    runs-on: macos-15
    steps: 
      - name: Checkout source code
        id: checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1

      - name: build
        id: build
        run: |
          MACOSX_DEPLOYMENT_TARGET=10.6 \
          ARCH="x86_64"
          CXXFLAGS="--target=x86_64-apple-macos10.6 -march=nocona" \
          CFLAGS="--target=x86_64-apple-macos10.6 -march=nocona"  \
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          archive: false
          path: |
            lib/libMacportsLegacySystem.B.dylib
          if-no-files-found: error
          retention-days: 7
